name: fitrack
description: "Real-time AI fitness coach — rep counting & form feedback"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  google_mlkit_pose_detection: ^0.12.0
  permission_handler: ^11.4.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
