/// Per-view ROM threshold defaults for the **biceps-curl FSM**.
///
/// One of three per-exercise `*_rom_defaults.dart` files. File naming follows
/// the exercise; provenance (telemetry vs literature vs other) is documented
/// in the doc-block below per the 2026-05-13 project convention.
///
/// PROVENANCE — telemetry-derived (PROJECT CONVENTION)
/// ────────────────────────────────────────────────────
/// All constants below come from live in-app diagnostic-session telemetry
/// (the "Curl debug session" Settings toggle) — NOT from an offline
/// video-clip analysis pipeline. Workflow when retuning:
///   1. Record a diagnostic session, paste the log to
///      `tools/dataset_analysis/data/telemetry/sessions/`.
///   2. Run `derive_thresholds_from_telemetry.py` — it auto-saves the
///      derived report to `data/telemetry/derived/`.
///   3. Paste the Dart snippet block from the derived report over the
///      matching `static const` block(s) below.
///
/// Highest-precedence layer in the three-tier resolver:
///   1. Telemetry-derived defaults (this file)         ← project convention
///   2. Pipeline-derived defaults  (`pipeline_rom_defaults.dart`, shelved)
///   3. Legacy hand-tuned constants (`constants.dart`)
///
/// Gated by [kUseCurlRomDefaults] in `constants.dart`. When the flag is on,
/// `RomThresholds.global(view)` consults [forView] first; if the view has an
/// entry, it wins. Views with `null` entries fall through to whichever of the
/// two lower tiers is active.
///
/// Why this file is separate from `pipeline_rom_defaults.dart`:
///   1. The pipeline file is GENERATED by `tools/dataset_analysis/scripts/
///      generate_dart_v2.py`. Re-running it overwrites manual edits silently.
///   2. The telemetry tier survives regeneration, so future A/B comparisons
///      between the pipeline output and a telemetry session are trivial: just
///      flip the two flags.
///   3. Per-view granularity — each view can independently opt into telemetry
///      values without forcing the others.
///
/// PROVENANCE — front bucket
/// ─────────────────────────
/// Source: diagnostic-mode session 2026-04-26, single user, 13 unique reps
/// (post-deduplication of bilateral commits), front view, full-ROM curls.
/// Methodology:
///   * Per-rep extremes captured via `rep.extremes` telemetry with
///     `min_at_peak` correction for 2D-pose wrist-snap artifacts.
///   * Outlier rejection: median ± 2×MAD.
///   * Generalization tolerances applied above personal medians:
///       peak: median (~7°)  + 28° → 35°  (covers users with ~40° peak ROM)
///       start: median (~156°) − 8° → 148° (covers users who only extend to
///                                          ~145°)
///       end: start − 20° (mirrors `kProfileEndTolerance`)
///       peakExit: peak + 15° (mirrors `kCurlPeakExitGap`)
///
/// PROVENANCE — sideLeft / sideRight buckets
/// ─────────────────────────────────────────
/// Source: diagnostic session 2026-04-28, left-arm side view, --from-frames
/// mode (FSM thresholds were misconfigured so no rep.extremes were emitted;
/// reps were detected from raw angle_raw signal via local-min/max detector).
/// n=7 raw reps, 5 kept after 3.5×MAD rejection. Personal medians: peak=108.4°,
/// start=167.0°. Permissive level omitted — geometrically invalid for this
/// user's ROM (peakExit would exceed startAngle with +38° tolerance).
library;

import 'pipeline_rom_defaults.dart';
import 'types.dart';

class CurlRomDefaults {
  const CurlRomDefaults._();

  // Front-view defaults removed 2026-05 along with the front analyzer.
  // The `CurlCameraView.front` enum value is retained as a view-detector
  // fallback sentinel; the `forView` resolver returns null for it so
  // callers cascade to the next ROM tier.

  // ── Side-left defaults (derived 2026-04-28, --from-frames mode) ────────────
  // Source: diagnostic session 2026-04-28 (left-arm, side view).
  // 7 reps detected via local-min/max frame-signal detector; 5 kept after
  // 3.5×MAD outlier rejection. Personal medians: peak=108.4°, start=167.0°.
  // ICC=0.000 (single session), eff_n=5. Mirror-inverted session logged as
  // sideRight due to a known home-screen mapping bug — angles are identical
  // by bilateral symmetry so these constants apply to both views.

  static const CurlRomThresholdSet sideLeftStrict = CurlRomThresholdSet(
    startAngle: 162.0,
    peakAngle: 128.4,
    peakExitAngle: 143.4,
    endAngle: 148.4,
  );

  static const CurlRomThresholdSet sideLeftDefault = CurlRomThresholdSet(
    startAngle: 159.0,
    peakAngle: 136.4,
    peakExitAngle: 151.4,
    endAngle: 156.4,
  );

  // ── Side-right defaults (aliases of sideLeft — bilateral symmetry) ──────────
  // Elbow-angle geometry is identical across left/right in the 2D sagittal
  // projection. These are true Dart const aliases — changing the sideLeft
  // constants above automatically propagates here with no manual sync needed.
  // If a dedicated right-arm session is ever recorded, replace the alias with
  // an independent CurlRomThresholdSet derived from that session.
  static const CurlRomThresholdSet sideRightStrict = sideLeftStrict;
  static const CurlRomThresholdSet sideRightDefault = sideLeftDefault;

  /// Look up the telemetry-derived default for a given view and sensitivity.
  ///
  /// Returns null when no default is defined for that view — caller falls
  /// through to the next resolution tier.
  ///
  /// [sensitivity] defaults to medium so all existing callers compile unchanged.
  static CurlRomThresholdSet? forView(
    CurlCameraView view, [
    FeedbackSensitivity sensitivity = FeedbackSensitivity.medium,
  ]) {
    switch (view) {
      case CurlCameraView.front:
        // Front view removed 2026-05; sentinel only. Cascade to the next
        // ROM tier by returning null.
        return null;
      case CurlCameraView.sideLeft:
        return switch (sensitivity) {
          FeedbackSensitivity.high => sideLeftStrict,
          FeedbackSensitivity.medium => sideLeftDefault,
        };
      case CurlCameraView.sideRight:
        return switch (sensitivity) {
          FeedbackSensitivity.high => sideRightStrict,
          FeedbackSensitivity.medium => sideRightDefault,
        };
      case CurlCameraView.unknown:
        return null;
    }
  }
}
