/// Hand-curated per-view threshold overrides for the biceps-curl FSM.
///
/// Highest-precedence layer in the three-tier resolver:
///   override (this file) > generated (default_rom_thresholds.dart) > legacy
/// (constants.dart)
///
/// Gated by [kUseManualOverrides] in `constants.dart`. When the flag is on,
/// `RomThresholds.global(view)` consults [forView] first; if the view has
/// an entry, it wins. Views with `null` entries fall through to whichever
/// of the two lower tiers is active (data-driven flag decides).
///
/// Why a separate file rather than editing `default_rom_thresholds.dart`:
///   1. That file is GENERATED by `tools/dataset_analysis/scripts/
///      generate_dart_v2.py`. Re-running the pipeline overwrites manual
///      edits silently.
///   2. The override layer survives regeneration, so future A/B comparisons
///      between the pipeline output and a manual session are trivial: just
///      flip [kUseManualOverrides].
///   3. Per-view granularity — each view can independently opt into manual
///      values without forcing the others.
///
/// PROVENANCE — front bucket
/// ─────────────────────────
/// Source: diagnostic-mode session 2026-04-26, single user, 13 unique reps
/// (post-deduplication of bilateral commits), front view, full-ROM curls.
/// Methodology:
///   * Per-rep extremes captured via `rep.extremes` telemetry with
///     `min_at_peak` correction for 2D-pose wrist-snap artifacts.
///   * Outlier rejection: median ± 2×MAD.
///   * Generalization tolerances applied above personal medians:
///       peak: median (~7°)  + 28° → 35°  (covers users with ~40° peak ROM)
///       start: median (~156°) − 8° → 148° (covers users who only extend to
///                                          ~145°)
///       end: start − 20° (mirrors `kProfileEndTolerance`)
///       peakExit: peak + 15° (mirrors `kCurlPeakExitGap`)
///
/// PROVENANCE — sideLeft / sideRight buckets
/// ─────────────────────────────────────────
/// Currently null. The next diagnostic side-view session will populate them.
/// Until then, side views fall through to the data-driven or legacy layers.
library;

import 'default_rom_thresholds.dart';
import 'types.dart';

class ManualRomOverrides {
  const ManualRomOverrides._();

  /// Front-view manual override. Derived 2026-04-26 with generalization.
  static const CurlRomThresholdSet front = CurlRomThresholdSet(
    startAngle: 148.0,
    peakAngle: 35.0,
    peakExitAngle: 50.0,
    endAngle: 128.0,
  );

  /// Side-left override — null until a side-left session is captured.
  static const CurlRomThresholdSet? sideLeft = null;

  /// Side-right override — null until a side-right session is captured
  /// (or sideLeft mirroring is decided as authoritative).
  static const CurlRomThresholdSet? sideRight = null;

  /// Look up the manual override for a given view. Returns null when no
  /// override is defined for that view — caller falls through to the next
  /// resolution tier.
  static CurlRomThresholdSet? forView(CurlCameraView view) {
    switch (view) {
      case CurlCameraView.front:
        return front;
      case CurlCameraView.sideLeft:
        return sideLeft;
      case CurlCameraView.sideRight:
        return sideRight;
      case CurlCameraView.unknown:
        // No override for unknown — let the lower tiers handle the
        // pre-detection fallback (which currently picks side-view as the
        // most anatomically accurate projection).
        return null;
    }
  }
}
